### PR TITLE
bump asmjit.dll to use latest asmjit/asmtk

### PR DESCRIPTION
**Pull request by pmeerw**
this addresses issue https://github.com/x64dbg/x64dbg/issues/2782: xchg eax,eax in 64-bit must not be translated into 0x90 (nop)

### CODE REVIEW

**Comment by pmeerw** [comment]
you probably want to build the DLLs yourself again using branch bump-asmjit in https://github.com/pmeerw/asmjit_xedparse, and sign

**Comment by mrexodia** [comment]
Thanks, will update the deps soon-ish.

**Comment by justanotheranonymoususer** [comment]
@mrexodia can you pls update asmjit in x64dbg? It fixed some bugs around 2021 that I need but I think x64dbg was last updated in 2017?

**Comment by mrexodia** [comment]
Should be updated now.

**Pull request closed without merging**
